#pragma once
/* Pre-computed CRC32 hashes of NT function names (seed = 0xEDB88320).
 * Generated by tools/hasher.py -- do not edit manually.
 * No plaintext NT function names in the binary's .rodata section. */

#define HASH_NtAllocateVirtualMemory        0xE0762FEBU
#define HASH_NtProtectVirtualMemory         0x5C2D1A97U
#define HASH_NtCreateThreadEx               0x2073465AU
#define HASH_NtWriteVirtualMemory           0xE4879939U
#define HASH_NtQueueApcThread               0x235B0390U
#define HASH_NtOpenProcess                  0xDBF381B5U
#define HASH_NtOpenProcessToken             0xC67A0958U
