#!/usr/bin/env python3
"""Generate nt_hashes.h with pre-computed CRC32 constants for NT function names.

Usage:
    python3 tools/hasher.py > agent_code/nt_hashes.h

Add new function names to FUNCTIONS list as needed.
Seed matches kratos_crc32h() in evasion.c (0xEDB88320).
"""

FUNCTIONS = [
    "NtAllocateVirtualMemory",
    "NtProtectVirtualMemory",
    "NtCreateThreadEx",
    "NtWriteVirtualMemory",
    "NtQueueApcThread",
    "NtOpenProcess",
    "NtOpenProcessToken",
]


def crc32h(s: str) -> int:
    crc = 0xFFFFFFFF
    for c in s.encode():
        crc ^= c
        for _ in range(8):
            crc = (crc >> 1) ^ (0xEDB88320 & (-(crc & 1) & 0xFFFFFFFF))
    return (~crc) & 0xFFFFFFFF


def main() -> None:
    print("#pragma once")
    print("/* Pre-computed CRC32 hashes of NT function names (seed = 0xEDB88320).")
    print(" * Generated by tools/hasher.py -- do not edit manually.")
    print(" * No plaintext NT function names in the binary's .rodata section. */")
    print()
    for name in FUNCTIONS:
        h = crc32h(name)
        print(f"#define HASH_{name:<30} 0x{h:08X}U")


if __name__ == "__main__":
    main()
